name: "Terraform Provision Gym CRM Resources"

on:
  workflow_dispatch:
    inputs:
      customer_name:
        description: "Unique Customer Identifier"
        required: true
        type: string

jobs:
  provision-infra:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      TF_WORK_DIR: ./environments/dev
      TF_CLOUD_ORGANIZATION: "<your-terraform-cloud-org>"
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }} # make sure it's here clearly!

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORK_DIR }}
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform init

      - name: Select/Create Terraform Workspace
        working-directory: ${{ env.TF_WORK_DIR }}
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: |
          terraform workspace select -or-create ${{ github.event.inputs.customer_name }}

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORK_DIR }}
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: |
          terraform plan \
            -var="customer_name=${{ github.event.inputs.customer_name }}"

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORK_DIR }}
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: |
          terraform apply -auto-approve \
            -var="customer_name=${{ github.event.inputs.customer_name }}"
