name: "Terraform Provision Gym CRM Resources"

on:
  workflow_dispatch:
    inputs:
      customer_name:
        description: "Unique Customer Identifier (no spaces, lowercase recommended)"
        required: true
        type: string

jobs:
  provision-infra:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./environments/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: ./environments/dev
        run: |
          terraform plan \
            -var="customer_name=${{ github.event.inputs.customer_name }}"

      - name: Terraform Apply
        working-directory: ./environments/dev
        run: |
          terraform apply -auto-approve \
            -var="customer_name=${{ github.event.inputs.customer_name }}"
